// @generated by protoc-gen-es v2.2.3 with parameter "target=ts,import_extension=none"
// @generated from file salto/type/interval.proto (package salto.type, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file salto/type/interval.proto.
 */
export const file_salto_type_interval: GenFile = /*@__PURE__*/
  fileDesc("ChlzYWx0by90eXBlL2ludGVydmFsLnByb3RvEgpzYWx0by50eXBlImgKCEludGVydmFsEi4KCnN0YXJ0X3RpbWUYASABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEiwKCGVuZF90aW1lGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEKnAQoSY29tLnNhbHRvYXBpcy50eXBlQg1JbnRlcnZhbFByb3RvUAFaQWdpdGh1Yi5jb20vc2FsdG9hcGlzLWludGVybmFsL3NhbHRvYXBpcy1nby90eXBlL2ludGVydmFsO2ludGVydmFsqgIOU2FsdG9hcGlzLlR5cGXKAg5TYWx0b2FwaXNcVHlwZeICGkdQQk1ldGFkYXRhXFNhbHRvYXBpc1xUeXBlYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * Represents a time interval with a start and end time.
 *
 * @generated from message salto.type.Interval
 */
export type Interval = Message<"salto.type.Interval"> & {
  /**
   * The start time of the interval.
   *
   * @generated from field: google.protobuf.Timestamp start_time = 1;
   */
  startTime?: Timestamp;

  /**
   * The end time of the interval.
   *
   * @generated from field: google.protobuf.Timestamp end_time = 2;
   */
  endTime?: Timestamp;
};

/**
 * Describes the message salto.type.Interval.
 * Use `create(IntervalSchema)` to create a new message.
 */
export const IntervalSchema: GenMessage<Interval> = /*@__PURE__*/
  messageDesc(file_salto_type_interval, 0);

