// @generated by protoc-gen-es v1.10.0 with parameter "target=ts,import_extension=none"
// @generated from file salto/nebula/type/opening_mode.proto (package salto.nebula.type, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * Represents an opening mode.
 *
 * @generated from enum salto.nebula.type.OpeningMode
 */
export enum OpeningMode {
  /**
   * Unspecified
   *
   * @generated from enum value: OPENING_MODE_UNSPECIFIED = 0;
   */
  OPENING_MODE_UNSPECIFIED = 0,

  /**
   * Office.
   *
   * @generated from enum value: OFFICE = 1;
   */
  OFFICE = 1,

  /**
   * Toggle.
   *
   * @generated from enum value: TOGGLE = 2;
   */
  TOGGLE = 2,

  /**
   * Autolock.
   *
   * @generated from enum value: AUTOLOCK = 3;
   */
  AUTOLOCK = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(OpeningMode)
proto3.util.setEnumType(OpeningMode, "salto.nebula.type.OpeningMode", [
  { no: 0, name: "OPENING_MODE_UNSPECIFIED" },
  { no: 1, name: "OFFICE" },
  { no: 2, name: "TOGGLE" },
  { no: 3, name: "AUTOLOCK" },
]);

