// @generated by protoc-gen-es v2.10.0 with parameter "target=ts,import_extension=none"
// @generated from file salto/nebula/type/remote_operation.proto (package salto.nebula.type, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file salto/nebula/type/remote_operation.proto.
 */
export const file_salto_nebula_type_remote_operation: GenFile = /*@__PURE__*/
  fileDesc("CihzYWx0by9uZWJ1bGEvdHlwZS9yZW1vdGVfb3BlcmF0aW9uLnByb3RvEhFzYWx0by5uZWJ1bGEudHlwZSpXChVBcHBLZXlSZW1vdGVPcGVyYXRpb24SKAokQVBQX0tFWV9SRU1PVEVfT1BFUkFUSU9OX1VOU1BFQ0lGSUVEEAASCAoETE9DSxABEgoKBlVOTE9DSxACQt8BChljb20uc2FsdG9hcGlzLm5lYnVsYS50eXBlQhRSZW1vdGVPcGVyYXRpb25Qcm90b1ABWlZnaXRodWIuY29tL3NhbHRvYXBpcy1pbnRlcm5hbC9zYWx0b2FwaXMtZ28vbmVidWxhL3R5cGUvcmVtb3Rlb3BlcmF0aW9uO3JlbW90ZW9wZXJhdGlvbqoCFVNhbHRvYXBpcy5OZWJ1bGEuVHlwZcoCFVNhbHRvYXBpc1xOZWJ1bGFcVHlwZeICIUdQQk1ldGFkYXRhXFNhbHRvYXBpc1xOZWJ1bGFcVHlwZWIGcHJvdG8z");

/**
 * Specifies the remote operation supported by the app key.
 *
 * @generated from enum salto.nebula.type.AppKeyRemoteOperation
 */
export enum AppKeyRemoteOperation {
  /**
   * Unspecified or unknown remote operation.
   *
   * @generated from enum value: APP_KEY_REMOTE_OPERATION_UNSPECIFIED = 0;
   */
  APP_KEY_REMOTE_OPERATION_UNSPECIFIED = 0,

  /**
   * Locks the access point remotely.
   *
   * @generated from enum value: LOCK = 1;
   */
  LOCK = 1,

  /**
   * Unlocks the access point remotely.
   *
   * @generated from enum value: UNLOCK = 2;
   */
  UNLOCK = 2,
}

/**
 * Describes the enum salto.nebula.type.AppKeyRemoteOperation.
 */
export const AppKeyRemoteOperationSchema: GenEnum<AppKeyRemoteOperation> = /*@__PURE__*/
  enumDesc(file_salto_nebula_type_remote_operation, 0);

