// @generated by protoc-gen-es v2.10.0 with parameter "target=ts,import_extension=none"
// @generated from file salto/nebula/type/day_type.proto (package salto.nebula.type, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file salto/nebula/type/day_type.proto.
 */
export const file_salto_nebula_type_day_type: GenFile = /*@__PURE__*/
  fileDesc("CiBzYWx0by9uZWJ1bGEvdHlwZS9kYXlfdHlwZS5wcm90bxIRc2FsdG8ubmVidWxhLnR5cGUqWgoHRGF5VHlwZRIYChREQVlfVFlQRV9VTlNQRUNJRklFRBAAEgoKBk5PUk1BTBABEgsKB0hPTElEQVkQAhINCglTUEVDSUFMXzEQAxINCglTUEVDSUFMXzIQBELHAQoZY29tLnNhbHRvYXBpcy5uZWJ1bGEudHlwZUIMRGF5VHlwZVByb3RvUAFaRmdpdGh1Yi5jb20vc2FsdG9hcGlzLWludGVybmFsL3NhbHRvYXBpcy1nby9uZWJ1bGEvdHlwZS9kYXl0eXBlO2RheXR5cGWqAhVTYWx0b2FwaXMuTmVidWxhLlR5cGXKAhVTYWx0b2FwaXNcTmVidWxhXFR5cGXiAiFHUEJNZXRhZGF0YVxTYWx0b2FwaXNcTmVidWxhXFR5cGViBnByb3RvMw");

/**
 * Represents the day types.
 *
 * @generated from enum salto.nebula.type.DayType
 */
export enum DayType {
  /**
   * Unspecified
   *
   * @generated from enum value: DAY_TYPE_UNSPECIFIED = 0;
   */
  DAY_TYPE_UNSPECIFIED = 0,

  /**
   * Normal day
   *
   * @generated from enum value: NORMAL = 1;
   */
  NORMAL = 1,

  /**
   * Holidays
   *
   * @generated from enum value: HOLIDAY = 2;
   */
  HOLIDAY = 2,

  /**
   * Special day type 1
   *
   * @generated from enum value: SPECIAL_1 = 3;
   */
  SPECIAL_1 = 3,

  /**
   * Special day type 2
   *
   * @generated from enum value: SPECIAL_2 = 4;
   */
  SPECIAL_2 = 4,
}

/**
 * Describes the enum salto.nebula.type.DayType.
 */
export const DayTypeSchema: GenEnum<DayType> = /*@__PURE__*/
  enumDesc(file_salto_nebula_type_day_type, 0);

