// @generated by protoc-gen-es v2.2.3 with parameter "target=ts,import_extension=none"
// @generated from file salto/nebula/type/opening_mode.proto (package salto.nebula.type, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file salto/nebula/type/opening_mode.proto.
 */
export const file_salto_nebula_type_opening_mode: GenFile = /*@__PURE__*/
  fileDesc("CiRzYWx0by9uZWJ1bGEvdHlwZS9vcGVuaW5nX21vZGUucHJvdG8SEXNhbHRvLm5lYnVsYS50eXBlKlEKC09wZW5pbmdNb2RlEhwKGE9QRU5JTkdfTU9ERV9VTlNQRUNJRklFRBAAEgoKBk9GRklDRRABEgoKBlRPR0dMRRACEgwKCEFVVE9MT0NLEANC0wEKGWNvbS5zYWx0b2FwaXMubmVidWxhLnR5cGVCEE9wZW5pbmdNb2RlUHJvdG9QAVpOZ2l0aHViLmNvbS9zYWx0b2FwaXMtaW50ZXJuYWwvc2FsdG9hcGlzLWdvL25lYnVsYS90eXBlL29wZW5pbmdtb2RlO29wZW5pbmdtb2RlqgIVU2FsdG9hcGlzLk5lYnVsYS5UeXBlygIVU2FsdG9hcGlzXE5lYnVsYVxUeXBl4gIhR1BCTWV0YWRhdGFcU2FsdG9hcGlzXE5lYnVsYVxUeXBlYgZwcm90bzM");

/**
 * Represents an opening mode.
 *
 * @generated from enum salto.nebula.type.OpeningMode
 */
export enum OpeningMode {
  /**
   * Unspecified
   *
   * @generated from enum value: OPENING_MODE_UNSPECIFIED = 0;
   */
  OPENING_MODE_UNSPECIFIED = 0,

  /**
   * Office.
   *
   * @generated from enum value: OFFICE = 1;
   */
  OFFICE = 1,

  /**
   * Toggle.
   *
   * @generated from enum value: TOGGLE = 2;
   */
  TOGGLE = 2,

  /**
   * Autolock.
   *
   * @generated from enum value: AUTOLOCK = 3;
   */
  AUTOLOCK = 3,
}

/**
 * Describes the enum salto.nebula.type.OpeningMode.
 */
export const OpeningModeSchema: GenEnum<OpeningMode> = /*@__PURE__*/
  enumDesc(file_salto_nebula_type_opening_mode, 0);

