// @generated by protoc-gen-connect-es v1.3.0 with parameter "target=ts,import_extension=none"
// @generated from file salto/nebula/installation/v1/encrypted_payload.proto (package salto.nebula.installation.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { IngestEncryptedPayloadsRequest, IngestEncryptedPayloadsResponse } from "./encrypted_payload_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * This service is responsible for the ingestion of encrypted payloads.
 *
 * @generated from service salto.nebula.installation.v1.EncryptedPayloadService
 */
export const EncryptedPayloadService = {
  typeName: "salto.nebula.installation.v1.EncryptedPayloadService",
  methods: {
    /**
     * Ingest encrypted payloads
     *
     * Ingests encrypted payload for a given installation.
     *
     * @generated from rpc salto.nebula.installation.v1.EncryptedPayloadService.IngestEncryptedPayloads
     */
    ingestEncryptedPayloads: {
      name: "IngestEncryptedPayloads",
      I: IngestEncryptedPayloadsRequest,
      O: IngestEncryptedPayloadsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

