// @generated by protoc-gen-es v2.10.0 with parameter "target=ts,import_extension=none"
// @generated from file salto/nebula/installation/v1/encrypted_payload.proto (package salto.nebula.installation.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file salto/nebula/installation/v1/encrypted_payload.proto.
 */
export const file_salto_nebula_installation_v1_encrypted_payload: GenFile = /*@__PURE__*/
  fileDesc("CjRzYWx0by9uZWJ1bGEvaW5zdGFsbGF0aW9uL3YxL2VuY3J5cHRlZF9wYXlsb2FkLnByb3RvEhxzYWx0by5uZWJ1bGEuaW5zdGFsbGF0aW9uLnYxIlIKHkluZ2VzdEVuY3J5cHRlZFBheWxvYWRzUmVxdWVzdBIUCgxpbnN0YWxsYXRpb24YASABKAkSGgoSZW5jcnlwdGVkX3BheWxvYWRzGAIgAygMIiEKH0luZ2VzdEVuY3J5cHRlZFBheWxvYWRzUmVzcG9uc2UysgEKF0VuY3J5cHRlZFBheWxvYWRTZXJ2aWNlEpYBChdJbmdlc3RFbmNyeXB0ZWRQYXlsb2FkcxI8LnNhbHRvLm5lYnVsYS5pbnN0YWxsYXRpb24udjEuSW5nZXN0RW5jcnlwdGVkUGF5bG9hZHNSZXF1ZXN0Gj0uc2FsdG8ubmVidWxhLmluc3RhbGxhdGlvbi52MS5Jbmdlc3RFbmNyeXB0ZWRQYXlsb2Fkc1Jlc3BvbnNlQoQCCiRjb20uc2FsdG9hcGlzLm5lYnVsYS5pbnN0YWxsYXRpb24udjFCFUVuY3J5cHRlZFBheWxvYWRQcm90b1ABWk5naXRodWIuY29tL3NhbHRvYXBpcy1pbnRlcm5hbC9zYWx0b2FwaXMtZ28vbmVidWxhL2luc3RhbGxhdGlvbi92MTtpbnN0YWxsYXRpb26qAiBTYWx0b2FwaXMuTmVidWxhLkluc3RhbGxhdGlvbi5WMcoCIFNhbHRvYXBpc1xOZWJ1bGFcSW5zdGFsbGF0aW9uXFYx4gIsR1BCTWV0YWRhdGFcU2FsdG9hcGlzXE5lYnVsYVxJbnN0YWxsYXRpb25cVjFiBnByb3RvMw");

/**
 * The request message for [`IngestEncryptedPayloads`][salto.nebula.installation.v1.EncryptedPayloadService.IngestEncryptedPayloads]
 *
 * @generated from message salto.nebula.installation.v1.IngestEncryptedPayloadsRequest
 */
export type IngestEncryptedPayloadsRequest = Message<"salto.nebula.installation.v1.IngestEncryptedPayloadsRequest"> & {
  /**
   * The parent installation resource name.
   * For example: `installations/surelock-homes-hq`.
   *
   * @generated from field: string installation = 1;
   */
  installation: string;

  /**
   * The encrypted payloads to be ingested.
   *
   * @generated from field: repeated bytes encrypted_payloads = 2;
   */
  encryptedPayloads: Uint8Array[];
};

/**
 * Describes the message salto.nebula.installation.v1.IngestEncryptedPayloadsRequest.
 * Use `create(IngestEncryptedPayloadsRequestSchema)` to create a new message.
 */
export const IngestEncryptedPayloadsRequestSchema: GenMessage<IngestEncryptedPayloadsRequest> = /*@__PURE__*/
  messageDesc(file_salto_nebula_installation_v1_encrypted_payload, 0);

/**
 * The response message for [`IngestEncryptedPayloads`][salto.nebula.installation.v1.EncryptedPayloadService.IngestEncryptedPayloads]
 *
 * @generated from message salto.nebula.installation.v1.IngestEncryptedPayloadsResponse
 */
export type IngestEncryptedPayloadsResponse = Message<"salto.nebula.installation.v1.IngestEncryptedPayloadsResponse"> & {
};

/**
 * Describes the message salto.nebula.installation.v1.IngestEncryptedPayloadsResponse.
 * Use `create(IngestEncryptedPayloadsResponseSchema)` to create a new message.
 */
export const IngestEncryptedPayloadsResponseSchema: GenMessage<IngestEncryptedPayloadsResponse> = /*@__PURE__*/
  messageDesc(file_salto_nebula_installation_v1_encrypted_payload, 1);

/**
 * This service is responsible for the ingestion of encrypted payloads.
 *
 * @generated from service salto.nebula.installation.v1.EncryptedPayloadService
 */
export const EncryptedPayloadService: GenService<{
  /**
   * Ingest encrypted payloads
   *
   * Ingests encrypted payload for a given installation.
   *
   * @generated from rpc salto.nebula.installation.v1.EncryptedPayloadService.IngestEncryptedPayloads
   */
  ingestEncryptedPayloads: {
    methodKind: "unary";
    input: typeof IngestEncryptedPayloadsRequestSchema;
    output: typeof IngestEncryptedPayloadsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_salto_nebula_installation_v1_encrypted_payload, 0);

