// @generated by protoc-gen-es v2.2.3 with parameter "target=ts,import_extension=none"
// @generated from file salto/type/time_of_day.proto (package salto.type, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file salto/type/time_of_day.proto.
 */
export const file_salto_type_time_of_day: GenFile = /*@__PURE__*/
  fileDesc("ChxzYWx0by90eXBlL3RpbWVfb2ZfZGF5LnByb3RvEgpzYWx0by50eXBlIksKCVRpbWVPZkRheRINCgVob3VycxgBIAEoBRIPCgdtaW51dGVzGAIgASgFEg8KB3NlY29uZHMYAyABKAUSDQoFbmFub3MYBCABKAVCqgEKEmNvbS5zYWx0b2FwaXMudHlwZUIOVGltZU9mRGF5UHJvdG9QAVpDZ2l0aHViLmNvbS9zYWx0b2FwaXMtaW50ZXJuYWwvc2FsdG9hcGlzLWdvL3R5cGUvdGltZW9mZGF5O3RpbWVvZmRheaoCDlNhbHRvYXBpcy5UeXBlygIOU2FsdG9hcGlzXFR5cGXiAhpHUEJNZXRhZGF0YVxTYWx0b2FwaXNcVHlwZWIGcHJvdG8z");

/**
 * Represents a time of day. The date and time zone are either not significant
 * or are specified elsewhere. An API may chose to allow leap seconds. Related
 * types are [`salto.type.Date`][salto.type.Date] and
 * `google.protobuf.Timestamp`.
 *
 * @generated from message salto.type.TimeOfDay
 */
export type TimeOfDay = Message<"salto.type.TimeOfDay"> & {
  /**
   * Hours of day in 24 hour format. Should be from 0 to 23.
   *
   * @generated from field: int32 hours = 1;
   */
  hours: number;

  /**
   * Minutes of hour of day. Must be from 0 to 59.
   *
   * @generated from field: int32 minutes = 2;
   */
  minutes: number;

  /**
   * Seconds of minutes of the time. Must be from 0 to 59.
   *
   * @generated from field: int32 seconds = 3;
   */
  seconds: number;

  /**
   * Fractions of seconds in nanoseconds. Must be from 0 to 999,999,999.
   *
   * @generated from field: int32 nanos = 4;
   */
  nanos: number;
};

/**
 * Describes the message salto.type.TimeOfDay.
 * Use `create(TimeOfDaySchema)` to create a new message.
 */
export const TimeOfDaySchema: GenMessage<TimeOfDay> = /*@__PURE__*/
  messageDesc(file_salto_type_time_of_day, 0);

