// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file salto/nebula/serviceaccount/v1/service_account.proto (package salto.nebula.serviceaccount.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateServiceAccountKeyRequest, CreateServiceAccountRequest, DeleteServiceAccountKeyRequest, DeleteServiceAccountRequest, GetServiceAccountKeyRequest, GetServiceAccountRequest, ListServiceAccountKeysRequest, ListServiceAccountKeysResponse, ListServiceAccountsRequest, ListServiceAccountsResponse, ServiceAccount, ServiceAccountKey, UpdateServiceAccountRequest } from "./service_account_pb";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * A service account is a specialized account used by applications or services to
 * authenticate and interact with other applications or services, providing a secure
 * and controlled way to manage access to resources.
 *
 * @generated from service salto.nebula.serviceaccount.v1.ServiceAccountService
 */
export const ServiceAccountService = {
  typeName: "salto.nebula.serviceaccount.v1.ServiceAccountService",
  methods: {
    /**
     * Create a service account
     *
     * Creates a new service account.
     *
     * @generated from rpc salto.nebula.serviceaccount.v1.ServiceAccountService.CreateServiceAccount
     */
    createServiceAccount: {
      name: "CreateServiceAccount",
      I: CreateServiceAccountRequest,
      O: ServiceAccount,
      kind: MethodKind.Unary,
    },
    /**
     * Get a service account
     *
     * Retrieves an existing service account.
     *
     * @generated from rpc salto.nebula.serviceaccount.v1.ServiceAccountService.GetServiceAccount
     */
    getServiceAccount: {
      name: "GetServiceAccount",
      I: GetServiceAccountRequest,
      O: ServiceAccount,
      kind: MethodKind.Unary,
    },
    /**
     * List service accounts
     *
     * Returns a list of service accounts that have been previously created.
     *
     * @generated from rpc salto.nebula.serviceaccount.v1.ServiceAccountService.ListServiceAccounts
     */
    listServiceAccounts: {
      name: "ListServiceAccounts",
      I: ListServiceAccountsRequest,
      O: ListServiceAccountsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Update the service account
     *
     * Updates the existing service account.
     *
     * @generated from rpc salto.nebula.serviceaccount.v1.ServiceAccountService.UpdateServiceAccount
     */
    updateServiceAccount: {
      name: "UpdateServiceAccount",
      I: UpdateServiceAccountRequest,
      O: ServiceAccount,
      kind: MethodKind.Unary,
    },
    /**
     * Delete a service account
     *
     * Permanently deletes a service account. This cannot be undone.
     *
     * @generated from rpc salto.nebula.serviceaccount.v1.ServiceAccountService.DeleteServiceAccount
     */
    deleteServiceAccount: {
      name: "DeleteServiceAccount",
      I: DeleteServiceAccountRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * Create a service account key
     *
     * Creates a new service account key.
     *
     * @generated from rpc salto.nebula.serviceaccount.v1.ServiceAccountService.CreateServiceAccountKey
     */
    createServiceAccountKey: {
      name: "CreateServiceAccountKey",
      I: CreateServiceAccountKeyRequest,
      O: ServiceAccountKey,
      kind: MethodKind.Unary,
    },
    /**
     * Get a service account key
     *
     * Retrieves a specific service account key by its resource name.
     *
     * @generated from rpc salto.nebula.serviceaccount.v1.ServiceAccountService.GetServiceAccountKey
     */
    getServiceAccountKey: {
      name: "GetServiceAccountKey",
      I: GetServiceAccountKeyRequest,
      O: ServiceAccountKey,
      kind: MethodKind.Unary,
    },
    /**
     * List service account keys
     *
     * Returns a list of keys for a service account.
     *
     * @generated from rpc salto.nebula.serviceaccount.v1.ServiceAccountService.ListServiceAccountKeys
     */
    listServiceAccountKeys: {
      name: "ListServiceAccountKeys",
      I: ListServiceAccountKeysRequest,
      O: ListServiceAccountKeysResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Delete a service account key
     *
     * Permanently deletes a service account key.
     *
     * @generated from rpc salto.nebula.serviceaccount.v1.ServiceAccountService.DeleteServiceAccountKey
     */
    deleteServiceAccountKey: {
      name: "DeleteServiceAccountKey",
      I: DeleteServiceAccountKeyRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

