load("//:rules.bzl", "load_rules")

package(default_visibility = ["//:__subpackages__"])

load_rules(
    extra_info = {
        "generator": "es-legacy",
    },
    internal_dependencies = [
    ],
    lib_name = "auth",
)
